### ISSUE TITLE
The generated QR code do not scan

### ISSUE THREAD

**Issue by PierreCiholas** [tg123/qrcode-wow#1] opened 2020-09-24 03:27 UTC
Hey I've been trying to scan the generated QR codes but they don't seem valid, I tested with 2 differents apps on my phone (the most downloaded and highly ranked on Google Play store), and none of them worked. I installed another addon, WOWQR that can generate QR codes containing the url to the Warhead Classic page about your target and this one works. I've done a file compare of the QR encode library file your addon and the one that works and there are differences, perhpas you that can help you solve the issue.

**Comment by Nihilianth** [comment] 2022-02-19 08:30
changing f:SetBackdropColor(0,0,0); to f:SetBackdropColor(1, 1, 1); in CreateQRTip fixed it for me

**Comment by tg123** [comment] 2022-02-19 08:37
black -> white?
can you paste the bad image here?

**Comment by Nihilianth** [comment] 2022-02-19 08:46
@tg123 exactly. looks like the border color is important. I am using it on a 30300 client build if relevant.

 f:SetBackdropColor(0,0,0);
![image](https://user-images.githubusercontent.com/6731717/154793838-1fd6750f-aae6-4081-88d9-0ca60e530d8d.png)

f:SetBackdropColor(1, 1, 1); 
![image](https://user-images.githubusercontent.com/6731717/154793810-3c57d8da-c24b-4675-a184-968e5715701e.png)

**Comment by tg123** [comment] 2022-02-19 08:51
nothing to do with the client
tested with iphone camera, both of them work

maybe the cause is the background is not transparent and should be high contract to the image

**Comment by Nihilianth** [comment] 2022-02-19 09:19
@tg123 I'm using android. Tried it with Samsung integrated QR scanner and an app. Only the bottom one works.

**Comment by Nihilianth** [comment] 2022-02-19 09:21
Also, if you use https://www.onlinebarcodereader.com/ it only detects the bottom one aswell

I assume it just needs the "quiet zone". My guess is that increasing texture size by 2 blocks in each dimension and offsetting the data part would be the fix for this. 

EDIT:https://qrworld.wordpress.com/2011/08/09/the-quiet-zone/

**Comment by tg123** [comment] 2022-02-19 10:01
hmmm agree
could you please send a PR or I will fix it this weekend

**Closed as completed** 2022-02-22 00:19 UTC
